### ISSUE TITLE
v1 release checklist

### ISSUE THREAD

**Issue by rji** [intelsdi-x/snap-plugin-collector-mesos#23]
Now that this plugin has been implemented per the design/scope doc in #2, I think it's safe to say that we're ready to tag the plugin at v1 and release it upon the world. Below is a checklist that I've put together with the work needed to actually ship it.

- [x] Resolve outstanding issues (see #22, #24)
- [x] Update README to include instructions for downloading the plugin binary for Linux
- [x] Tag this repo at v1
- [x] Create a new GitHub release for the v1 tag
- [x] Upload plugin binaries to the v1 release
- [x] Update the GitHub repo description (proposed: "Collect metrics from an Apache Mesos cluster.")
- [x] Remove the GitHub "wiki" feature from this repo (we won't use it)
- [x] Make the repo public

Post-release cleanup:
- [x] Submit a PR to intelsdi-x/snap to include this plugin in the plugin catalog doc
- [x] Add Coveralls.io integration and update README with Coveralls.io badge
- [x] Update Travis CI README badge from travis-ci.com to travis-ci.org.

![ship-launch-floods-street](https://cloud.githubusercontent.com/assets/1910193/15802592/e11c039a-2a6b-11e6-9a84-7cdcdbbfe675.gif)

**Comment by rji** [comment]
All the outstanding tasks are now complete 💯
